name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check Out
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run dotnet format
        id: format
        uses: jfversluis/dotnet-format@v1.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          #only-changed-files: true # only works for PRs
          #workspace: "Ghis.Windows.Controls.sln"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build On release
        run: dotnet build -c Release --no-restore

      - name: Test On Debug
        run: dotnet test -c Debug --no-restore --verbosity normal
