name: Build
on: [push, pull_request] # Trigger when someone pushs or dens PR

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build On release
        run: dotnet build -c Release --no-restore

      - name: Test On Debug
        run: dotnet test -c Debug --no-restore --verbosity normal --filter TestCategory!=WpfUserControlTestMethod
